base:
  image: ihsw/raml-family
test-base:
  extends:
    service: base
  command: npm test --silent

web:
  extends:
    service: base
  ports:
    - 80:80
web-dev:
  extends:
    service: web
  volumes:
    - ./app:/srv/app

test:
  extends:
    service: test-base
test-dev:
  extends:
    service: test-base
  volumes:
    - ./app:/srv/app
